---
# Logger configuration.
logger:
  # Log level.
  #
  # Value: emerg | alert | crit | error | warning | notice | info | debug
  level: debug

  # Logger backends.
  #
  # Value: array
  backends:
  -
    # Backend type.
    #
    # Value: file | syslog
    type: file

    # File backend configuration.
    file:
      # Destination.
      #
      # Value: stdout | stderr | /path/to/file
      destination: stderr

# Database configuration.
db:
  # Storage type.
  #
  # Value: sql
  type: sql

  # SQL DB configuration.
  sql:
    # Driver
    #
    # Value: sqlite3 | mysql | pgx
    driver: sqlite3

    # DSN
    #
    # Value: string
    dsn: ./db.sqlite3

    # Migrate automatically on start
    #
    # Value: boolean
    auto-migrate: true

# Hasher configuration.
hasher:
  # Alphabet.
  #
  # Value: string
  alphabet: 0123456789abcdef
  # Salt.
  #
  # Value: string
  salt: No paste on Sunday. No blasted pastes today! No, sir. Not one single bloody paste. Not one!
  # Minimal hash length.
  #
  # Value: uint
  min-length: 8

# WebServer configuration.
webserver:
  # Static assets path on disk.
  #
  # Value: embedded | /path/to/dir
  static-path: ./pkg/webserver/static

  # Template files path on disk.
  #
  # Value: embedded | /path/to/dir
  templates-path: ./pkg/webserver/templates

  # Listen address.
  #
  # Value: host:port
  listen-address: 0.0.0.0:1337

  # Proxy header.
  #
  # Value: string
  proxy-header:

  # TLS certificate.
  #
  # Value: /path/to/file
  tls-cert:

  # TLS key.
  #
  # Value: /path/to/file
  tls-key:

  # Relative URL root.
  #
  # Value: string
  relative-url-root: /p
