package codemirror

// revive:disable:line-length-limit

// Modes ...
var Modes = []Mode{
	{
		Name:       "Auto",
		Mode:       "null",
		MimeTypes:  []string{""},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Plain Text",
		Mode:       "null",
		MimeTypes:  []string{"text/plain"},
		Extensions: []string{"txt", "text", "conf", "def", "list", "log"},
		Aliases:    []string{},
	},
	{
		Name:       "APL",
		Mode:       "apl",
		MimeTypes:  []string{"text/apl"},
		Extensions: []string{"dyalog", "apl"},
		Aliases:    []string{},
	},
	{
		Name:       "PGP",
		Mode:       "asciiarmor",
		MimeTypes:  []string{"application/pgp", "application/pgp-encrypted", "application/pgp-keys", "application/pgp-signature"},
		Extensions: []string{"asc", "pgp", "sig"},
		Aliases:    []string{},
	},
	{
		Name:       "ASN.1",
		Mode:       "asn.1",
		MimeTypes:  []string{"text/x-ttcn-asn"},
		Extensions: []string{"asn", "asn1"},
		Aliases:    []string{},
	},
	{
		Name:       "Asterisk",
		Mode:       "asterisk",
		MimeTypes:  []string{"text/x-asterisk"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Brainfuck",
		Mode:       "brainfuck",
		MimeTypes:  []string{"text/x-brainfuck"},
		Extensions: []string{"b", "bf"},
		Aliases:    []string{},
	},
	{
		Name:       "C",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-csrc"},
		Extensions: []string{"c", "h", "ino"},
		Aliases:    []string{},
	},
	{
		Name:       "C++",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-c++src"},
		Extensions: []string{"cpp", "c++", "cc", "cxx", "hpp", "h++", "hh", "hxx"},
		Aliases:    []string{"cpp"},
	},
	{
		Name:       "Cobol",
		Mode:       "cobol",
		MimeTypes:  []string{"text/x-cobol"},
		Extensions: []string{"cob", "cpy"},
		Aliases:    []string{},
	},
	{
		Name:       "C#",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-csharp"},
		Extensions: []string{"cs"},
		Aliases:    []string{"csharp", "cs"},
	},
	{
		Name:       "Clojure",
		Mode:       "clojure",
		MimeTypes:  []string{"text/x-clojure"},
		Extensions: []string{"clj", "cljc", "cljx"},
		Aliases:    []string{},
	},
	{
		Name:       "ClojureScript",
		Mode:       "clojure",
		MimeTypes:  []string{"text/x-clojurescript"},
		Extensions: []string{"cljs"},
		Aliases:    []string{},
	},
	{
		Name:       "Closure Stylesheets (GSS)",
		Mode:       "css",
		MimeTypes:  []string{"text/x-gss"},
		Extensions: []string{"gss"},
		Aliases:    []string{},
	},
	{
		Name:       "CMake",
		Mode:       "cmake",
		MimeTypes:  []string{"text/x-cmake"},
		Extensions: []string{"cmake", "cmake.in"},
		Aliases:    []string{},
	},
	{
		Name:       "CoffeeScript",
		Mode:       "coffeescript",
		MimeTypes:  []string{"application/vnd.coffeescript", "text/coffeescript", "text/x-coffeescript"},
		Extensions: []string{"coffee"},
		Aliases:    []string{"coffee", "coffee-script"},
	},
	{
		Name:       "Common Lisp",
		Mode:       "commonlisp",
		MimeTypes:  []string{"text/x-common-lisp"},
		Extensions: []string{"cl", "lisp", "el"},
		Aliases:    []string{"lisp"},
	},
	{
		Name:       "Cypher",
		Mode:       "cypher",
		MimeTypes:  []string{"application/x-cypher-query"},
		Extensions: []string{"cyp", "cypher"},
		Aliases:    []string{},
	},
	{
		Name:       "Cython",
		Mode:       "python",
		MimeTypes:  []string{"text/x-cython"},
		Extensions: []string{"pyx", "pxd", "pxi"},
		Aliases:    []string{},
	},
	{
		Name:       "Crystal",
		Mode:       "crystal",
		MimeTypes:  []string{"text/x-crystal"},
		Extensions: []string{"cr"},
		Aliases:    []string{},
	},
	{
		Name:       "CSS",
		Mode:       "css",
		MimeTypes:  []string{"text/css"},
		Extensions: []string{"css"},
		Aliases:    []string{},
	},
	{
		Name:       "CQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-cassandra"},
		Extensions: []string{"cql"},
		Aliases:    []string{},
	},
	{
		Name:       "D",
		Mode:       "d",
		MimeTypes:  []string{"text/x-d"},
		Extensions: []string{"d"},
		Aliases:    []string{},
	},
	{
		Name:       "Dart",
		Mode:       "dart",
		MimeTypes:  []string{"application/dart", "text/x-dart"},
		Extensions: []string{"dart"},
		Aliases:    []string{},
	},
	{
		Name:       "diff",
		Mode:       "diff",
		MimeTypes:  []string{"text/x-diff"},
		Extensions: []string{"diff", "patch"},
		Aliases:    []string{},
	},
	{
		Name:       "Django",
		Mode:       "django",
		MimeTypes:  []string{"text/x-django"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Dockerfile",
		Mode:       "dockerfile",
		MimeTypes:  []string{"text/x-dockerfile"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "DTD",
		Mode:       "dtd",
		MimeTypes:  []string{"application/xml-dtd"},
		Extensions: []string{"dtd"},
		Aliases:    []string{},
	},
	{
		Name:       "Dylan",
		Mode:       "dylan",
		MimeTypes:  []string{"text/x-dylan"},
		Extensions: []string{"dylan", "dyl", "intr"},
		Aliases:    []string{},
	},
	{
		Name:       "EBNF",
		Mode:       "ebnf",
		MimeTypes:  []string{"text/x-ebnf"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "ECL",
		Mode:       "ecl",
		MimeTypes:  []string{"text/x-ecl"},
		Extensions: []string{"ecl"},
		Aliases:    []string{},
	},
	{
		Name:       "edn",
		Mode:       "clojure",
		MimeTypes:  []string{"application/edn"},
		Extensions: []string{"edn"},
		Aliases:    []string{},
	},
	{
		Name:       "Eiffel",
		Mode:       "eiffel",
		MimeTypes:  []string{"text/x-eiffel"},
		Extensions: []string{"e"},
		Aliases:    []string{},
	},
	{
		Name:       "Elm",
		Mode:       "elm",
		MimeTypes:  []string{"text/x-elm"},
		Extensions: []string{"elm"},
		Aliases:    []string{},
	},
	{
		Name:       "Embedded JavaScript",
		Mode:       "htmlembedded",
		MimeTypes:  []string{"application/x-ejs"},
		Extensions: []string{"ejs"},
		Aliases:    []string{},
	},
	{
		Name:       "Embedded Ruby",
		Mode:       "htmlembedded",
		MimeTypes:  []string{"application/x-erb"},
		Extensions: []string{"erb"},
		Aliases:    []string{},
	},
	{
		Name:       "Erlang",
		Mode:       "erlang",
		MimeTypes:  []string{"text/x-erlang"},
		Extensions: []string{"erl"},
		Aliases:    []string{},
	},
	{
		Name:       "Esper",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-esper"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Factor",
		Mode:       "factor",
		MimeTypes:  []string{"text/x-factor"},
		Extensions: []string{"factor"},
		Aliases:    []string{},
	},
	{
		Name:       "FCL",
		Mode:       "fcl",
		MimeTypes:  []string{"text/x-fcl"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Forth",
		Mode:       "forth",
		MimeTypes:  []string{"text/x-forth"},
		Extensions: []string{"forth", "fth", "4th"},
		Aliases:    []string{},
	},
	{
		Name:       "Fortran",
		Mode:       "fortran",
		MimeTypes:  []string{"text/x-fortran"},
		Extensions: []string{"f", "for", "f77", "f90", "f95"},
		Aliases:    []string{},
	},
	{
		Name:       "F#",
		Mode:       "mllike",
		MimeTypes:  []string{"text/x-fsharp"},
		Extensions: []string{"fs"},
		Aliases:    []string{"fsharp"},
	},
	{
		Name:       "Gas",
		Mode:       "gas",
		MimeTypes:  []string{"text/x-gas"},
		Extensions: []string{"s"},
		Aliases:    []string{},
	},
	{
		Name:       "Gherkin",
		Mode:       "gherkin",
		MimeTypes:  []string{"text/x-feature"},
		Extensions: []string{"feature"},
		Aliases:    []string{},
	},
	{
		Name:       "GitHub Flavored Markdown",
		Mode:       "gfm",
		MimeTypes:  []string{"text/x-gfm"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Go",
		Mode:       "go",
		MimeTypes:  []string{"text/x-go"},
		Extensions: []string{"go"},
		Aliases:    []string{},
	},
	{
		Name:       "Groovy",
		Mode:       "groovy",
		MimeTypes:  []string{"text/x-groovy"},
		Extensions: []string{"groovy", "gradle"},
		Aliases:    []string{},
	},
	{
		Name:       "HAML",
		Mode:       "haml",
		MimeTypes:  []string{"text/x-haml"},
		Extensions: []string{"haml"},
		Aliases:    []string{},
	},
	{
		Name:       "Haskell",
		Mode:       "haskell",
		MimeTypes:  []string{"text/x-haskell"},
		Extensions: []string{"hs"},
		Aliases:    []string{},
	},
	{
		Name:       "Haskell (Literate)",
		Mode:       "haskell-literate",
		MimeTypes:  []string{"text/x-literate-haskell"},
		Extensions: []string{"lhs"},
		Aliases:    []string{},
	},
	{
		Name:       "Haxe",
		Mode:       "haxe",
		MimeTypes:  []string{"text/x-haxe"},
		Extensions: []string{"hx"},
		Aliases:    []string{},
	},
	{
		Name:       "HXML",
		Mode:       "haxe",
		MimeTypes:  []string{"text/x-hxml"},
		Extensions: []string{"hxml"},
		Aliases:    []string{},
	},
	{
		Name:       "ASP.NET",
		Mode:       "htmlembedded",
		MimeTypes:  []string{"application/x-aspx"},
		Extensions: []string{"aspx"},
		Aliases:    []string{"asp", "aspx"},
	},
	{
		Name:       "HTML",
		Mode:       "htmlmixed",
		MimeTypes:  []string{"text/html"},
		Extensions: []string{"html", "htm", "handlebars", "hbs"},
		Aliases:    []string{"xhtml"},
	},
	{
		Name:       "HTTP",
		Mode:       "http",
		MimeTypes:  []string{"message/http"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "IDL",
		Mode:       "idl",
		MimeTypes:  []string{"text/x-idl"},
		Extensions: []string{"pro"},
		Aliases:    []string{},
	},
	{
		Name:       "Pug",
		Mode:       "pug",
		MimeTypes:  []string{"text/x-pug"},
		Extensions: []string{"jade", "pug"},
		Aliases:    []string{"jade"},
	},
	{
		Name:       "Java",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-java"},
		Extensions: []string{"java"},
		Aliases:    []string{},
	},
	{
		Name:       "Java Server Pages",
		Mode:       "htmlembedded",
		MimeTypes:  []string{"application/x-jsp"},
		Extensions: []string{"jsp"},
		Aliases:    []string{"jsp"},
	},
	{
		Name:       "JavaScript",
		Mode:       "javascript",
		MimeTypes:  []string{"text/javascript", "text/ecmascript", "application/javascript", "application/x-javascript", "application/ecmascript"},
		Extensions: []string{"js"},
		Aliases:    []string{"ecmascript", "js", "node"},
	},
	{
		Name:       "JSON",
		Mode:       "javascript",
		MimeTypes:  []string{"application/json", "application/x-json"},
		Extensions: []string{"json", "map"},
		Aliases:    []string{"json5"},
	},
	{
		Name:       "JSON-LD",
		Mode:       "javascript",
		MimeTypes:  []string{"application/ld+json"},
		Extensions: []string{"jsonld"},
		Aliases:    []string{"jsonld"},
	},
	{
		Name:       "JSX",
		Mode:       "jsx",
		MimeTypes:  []string{"text/jsx"},
		Extensions: []string{"jsx"},
		Aliases:    []string{},
	},
	{
		Name:       "Jinja2",
		Mode:       "jinja2",
		MimeTypes:  []string{"text/jinja2"},
		Extensions: []string{"j2", "jinja", "jinja2"},
		Aliases:    []string{},
	},
	{
		Name:       "Julia",
		Mode:       "julia",
		MimeTypes:  []string{"text/x-julia"},
		Extensions: []string{"jl"},
		Aliases:    []string{},
	},
	{
		Name:       "Kotlin",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-kotlin"},
		Extensions: []string{"kt"},
		Aliases:    []string{},
	},
	{
		Name:       "LESS",
		Mode:       "css",
		MimeTypes:  []string{"text/x-less"},
		Extensions: []string{"less"},
		Aliases:    []string{},
	},
	{
		Name:       "LiveScript",
		Mode:       "livescript",
		MimeTypes:  []string{"text/x-livescript"},
		Extensions: []string{"ls"},
		Aliases:    []string{"ls"},
	},
	{
		Name:       "Lua",
		Mode:       "lua",
		MimeTypes:  []string{"text/x-lua"},
		Extensions: []string{"lua"},
		Aliases:    []string{},
	},
	{
		Name:       "Markdown",
		Mode:       "markdown",
		MimeTypes:  []string{"text/x-markdown"},
		Extensions: []string{"markdown", "md", "mkd"},
		Aliases:    []string{},
	},
	{
		Name:       "mIRC",
		Mode:       "mirc",
		MimeTypes:  []string{"text/mirc"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "MariaDB SQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-mariadb"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Mathematica",
		Mode:       "mathematica",
		MimeTypes:  []string{"text/x-mathematica"},
		Extensions: []string{"m", "nb", "wl", "wls"},
		Aliases:    []string{},
	},
	{
		Name:       "Modelica",
		Mode:       "modelica",
		MimeTypes:  []string{"text/x-modelica"},
		Extensions: []string{"mo"},
		Aliases:    []string{},
	},
	{
		Name:       "MUMPS",
		Mode:       "mumps",
		MimeTypes:  []string{"text/x-mumps"},
		Extensions: []string{"mps"},
		Aliases:    []string{},
	},
	{
		Name:       "MS SQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-mssql"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "mbox",
		Mode:       "mbox",
		MimeTypes:  []string{"application/mbox"},
		Extensions: []string{"mbox"},
		Aliases:    []string{},
	},
	{
		Name:       "MySQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-mysql"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Nginx",
		Mode:       "nginx",
		MimeTypes:  []string{"text/x-nginx-conf"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "NSIS",
		Mode:       "nsis",
		MimeTypes:  []string{"text/x-nsis"},
		Extensions: []string{"nsh", "nsi"},
		Aliases:    []string{},
	},
	{
		Name:       "NTriples",
		Mode:       "ntriples",
		MimeTypes:  []string{"application/n-triples", "application/n-quads", "text/n-triples"},
		Extensions: []string{"nt", "nq"},
		Aliases:    []string{},
	},
	{
		Name:       "Objective-C",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-objectivec"},
		Extensions: []string{"m"},
		Aliases:    []string{"objective-c", "objc"},
	},
	{
		Name:       "Objective-C++",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-objectivec++"},
		Extensions: []string{"mm"},
		Aliases:    []string{"objective-c++", "objc++"},
	},
	{
		Name:       "OCaml",
		Mode:       "mllike",
		MimeTypes:  []string{"text/x-ocaml"},
		Extensions: []string{"ml", "mli", "mll", "mly"},
		Aliases:    []string{},
	},
	{
		Name:       "Octave",
		Mode:       "octave",
		MimeTypes:  []string{"text/x-octave"},
		Extensions: []string{"m"},
		Aliases:    []string{},
	},
	{
		Name:       "Oz",
		Mode:       "oz",
		MimeTypes:  []string{"text/x-oz"},
		Extensions: []string{"oz"},
		Aliases:    []string{},
	},
	{
		Name:       "Pascal",
		Mode:       "pascal",
		MimeTypes:  []string{"text/x-pascal"},
		Extensions: []string{"p", "pas"},
		Aliases:    []string{},
	},
	{
		Name:       "PEG.js",
		Mode:       "pegjs",
		MimeTypes:  []string{"null"},
		Extensions: []string{"jsonld"},
		Aliases:    []string{},
	},
	{
		Name:       "Perl",
		Mode:       "perl",
		MimeTypes:  []string{"text/x-perl"},
		Extensions: []string{"pl", "pm"},
		Aliases:    []string{},
	},
	{
		Name:       "PHP",
		Mode:       "php",
		MimeTypes:  []string{"text/x-php", "application/x-httpd-php", "application/x-httpd-php-open"},
		Extensions: []string{"php", "php3", "php4", "php5", "php7", "phtml"},
		Aliases:    []string{},
	},
	{
		Name:       "Pig",
		Mode:       "pig",
		MimeTypes:  []string{"text/x-pig"},
		Extensions: []string{"pig"},
		Aliases:    []string{},
	},
	{
		Name:       "PLSQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-plsql"},
		Extensions: []string{"pls"},
		Aliases:    []string{},
	},
	{
		Name:       "PostgreSQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-pgsql"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "PowerShell",
		Mode:       "powershell",
		MimeTypes:  []string{"application/x-powershell"},
		Extensions: []string{"ps1", "psd1", "psm1"},
		Aliases:    []string{},
	},
	{
		Name:       "Properties files",
		Mode:       "properties",
		MimeTypes:  []string{"text/x-properties"},
		Extensions: []string{"properties", "ini", "in"},
		Aliases:    []string{"ini", "properties"},
	},
	{
		Name:       "ProtoBuf",
		Mode:       "protobuf",
		MimeTypes:  []string{"text/x-protobuf"},
		Extensions: []string{"proto"},
		Aliases:    []string{},
	},
	{
		Name:       "Python",
		Mode:       "python",
		MimeTypes:  []string{"text/x-python"},
		Extensions: []string{"BUILD", "bzl", "py", "pyw"},
		Aliases:    []string{},
	},
	{
		Name:       "Puppet",
		Mode:       "puppet",
		MimeTypes:  []string{"text/x-puppet"},
		Extensions: []string{"pp"},
		Aliases:    []string{},
	},
	{
		Name:       "Q",
		Mode:       "q",
		MimeTypes:  []string{"text/x-q"},
		Extensions: []string{"q"},
		Aliases:    []string{},
	},
	{
		Name:       "R",
		Mode:       "r",
		MimeTypes:  []string{"text/x-rsrc"},
		Extensions: []string{"r", "R"},
		Aliases:    []string{"rscript"},
	},
	{
		Name:       "reStructuredText",
		Mode:       "rst",
		MimeTypes:  []string{"text/x-rst"},
		Extensions: []string{"rst"},
		Aliases:    []string{"rst"},
	},
	{
		Name:       "RPM Changes",
		Mode:       "rpm",
		MimeTypes:  []string{"text/x-rpm-changes"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "RPM Spec",
		Mode:       "rpm",
		MimeTypes:  []string{"text/x-rpm-spec"},
		Extensions: []string{"spec"},
		Aliases:    []string{},
	},
	{
		Name:       "Ruby",
		Mode:       "ruby",
		MimeTypes:  []string{"text/x-ruby"},
		Extensions: []string{"rb"},
		Aliases:    []string{"jruby", "macruby", "rake", "rb", "rbx"},
	},
	{
		Name:       "Rust",
		Mode:       "rust",
		MimeTypes:  []string{"text/x-rustsrc"},
		Extensions: []string{"rs"},
		Aliases:    []string{},
	},
	{
		Name:       "SAS",
		Mode:       "sas",
		MimeTypes:  []string{"text/x-sas"},
		Extensions: []string{"sas"},
		Aliases:    []string{},
	},
	{
		Name:       "Sass",
		Mode:       "sass",
		MimeTypes:  []string{"text/x-sass"},
		Extensions: []string{"sass"},
		Aliases:    []string{},
	},
	{
		Name:       "Scala",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-scala"},
		Extensions: []string{"scala"},
		Aliases:    []string{},
	},
	{
		Name:       "Scheme",
		Mode:       "scheme",
		MimeTypes:  []string{"text/x-scheme"},
		Extensions: []string{"scm", "ss"},
		Aliases:    []string{},
	},
	{
		Name:       "SCSS",
		Mode:       "css",
		MimeTypes:  []string{"text/x-scss"},
		Extensions: []string{"scss"},
		Aliases:    []string{},
	},
	{
		Name:       "Shell",
		Mode:       "shell",
		MimeTypes:  []string{"text/x-sh", "application/x-sh"},
		Extensions: []string{"sh", "ksh", "bash"},
		Aliases:    []string{"bash", "sh", "zsh"},
	},
	{
		Name:       "Sieve",
		Mode:       "sieve",
		MimeTypes:  []string{"application/sieve"},
		Extensions: []string{"siv", "sieve"},
		Aliases:    []string{},
	},
	{
		Name:       "Slim",
		Mode:       "slim",
		MimeTypes:  []string{"text/x-slim", "application/x-slim"},
		Extensions: []string{"slim"},
		Aliases:    []string{},
	},
	{
		Name:       "Smalltalk",
		Mode:       "smalltalk",
		MimeTypes:  []string{"text/x-stsrc"},
		Extensions: []string{"st"},
		Aliases:    []string{},
	},
	{
		Name:       "Smarty",
		Mode:       "smarty",
		MimeTypes:  []string{"text/x-smarty"},
		Extensions: []string{"tpl"},
		Aliases:    []string{},
	},
	{
		Name:       "Solr",
		Mode:       "solr",
		MimeTypes:  []string{"text/x-solr"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "SML",
		Mode:       "mllike",
		MimeTypes:  []string{"text/x-sml"},
		Extensions: []string{"sml", "sig", "fun", "smackspec"},
		Aliases:    []string{},
	},
	{
		Name:       "Soy",
		Mode:       "soy",
		MimeTypes:  []string{"text/x-soy"},
		Extensions: []string{"soy"},
		Aliases:    []string{"closure template"},
	},
	{
		Name:       "SPARQL",
		Mode:       "sparql",
		MimeTypes:  []string{"application/sparql-query"},
		Extensions: []string{"rq", "sparql"},
		Aliases:    []string{"sparul"},
	},
	{
		Name:       "Spreadsheet",
		Mode:       "spreadsheet",
		MimeTypes:  []string{"text/x-spreadsheet"},
		Extensions: []string{},
		Aliases:    []string{"excel", "formula"},
	},
	{
		Name:       "SQL",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-sql"},
		Extensions: []string{"sql"},
		Aliases:    []string{},
	},
	{
		Name:       "SQLite",
		Mode:       "sql",
		MimeTypes:  []string{"text/x-sqlite"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Squirrel",
		Mode:       "clike",
		MimeTypes:  []string{"text/x-squirrel"},
		Extensions: []string{"nut"},
		Aliases:    []string{},
	},
	{
		Name:       "Stylus",
		Mode:       "stylus",
		MimeTypes:  []string{"text/x-styl"},
		Extensions: []string{"styl"},
		Aliases:    []string{},
	},
	{
		Name:       "Swift",
		Mode:       "swift",
		MimeTypes:  []string{"text/x-swift"},
		Extensions: []string{"swift"},
		Aliases:    []string{},
	},
	{
		Name:       "sTeX",
		Mode:       "stex",
		MimeTypes:  []string{"text/x-stex"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "LaTeX",
		Mode:       "stex",
		MimeTypes:  []string{"text/x-latex"},
		Extensions: []string{"text", "ltx", "tex"},
		Aliases:    []string{"tex"},
	},
	{
		Name:       "SystemVerilog",
		Mode:       "verilog",
		MimeTypes:  []string{"text/x-systemverilog"},
		Extensions: []string{"v", "sv", "svh"},
		Aliases:    []string{},
	},
	{
		Name:       "Tcl",
		Mode:       "tcl",
		MimeTypes:  []string{"text/x-tcl"},
		Extensions: []string{"tcl"},
		Aliases:    []string{},
	},
	{
		Name:       "Textile",
		Mode:       "textile",
		MimeTypes:  []string{"text/x-textile"},
		Extensions: []string{"textile"},
		Aliases:    []string{},
	},
	{
		Name:       "TiddlyWiki",
		Mode:       "tiddlywiki",
		MimeTypes:  []string{"text/x-tiddlywiki"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Tiki wiki",
		Mode:       "tiki",
		MimeTypes:  []string{"text/tiki"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "TOML",
		Mode:       "toml",
		MimeTypes:  []string{"text/x-toml"},
		Extensions: []string{"toml"},
		Aliases:    []string{},
	},
	{
		Name:       "Tornado",
		Mode:       "tornado",
		MimeTypes:  []string{"text/x-tornado"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "troff",
		Mode:       "troff",
		MimeTypes:  []string{"text/troff"},
		Extensions: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"},
		Aliases:    []string{},
	},
	{
		Name:       "TTCN",
		Mode:       "ttcn",
		MimeTypes:  []string{"text/x-ttcn"},
		Extensions: []string{"ttcn", "ttcn3", "ttcnpp"},
		Aliases:    []string{},
	},
	{
		Name:       "TTCN_CFG",
		Mode:       "ttcn-cfg",
		MimeTypes:  []string{"text/x-ttcn-cfg"},
		Extensions: []string{"cfg"},
		Aliases:    []string{},
	},
	{
		Name:       "Turtle",
		Mode:       "turtle",
		MimeTypes:  []string{"text/turtle"},
		Extensions: []string{"ttl"},
		Aliases:    []string{},
	},
	{
		Name:       "TypeScript",
		Mode:       "javascript",
		MimeTypes:  []string{"application/typescript"},
		Extensions: []string{"ts"},
		Aliases:    []string{"ts"},
	},
	{
		Name:       "TypeScript-JSX",
		Mode:       "jsx",
		MimeTypes:  []string{"text/typescript-jsx"},
		Extensions: []string{"tsx"},
		Aliases:    []string{"tsx"},
	},
	{
		Name:       "Twig",
		Mode:       "twig",
		MimeTypes:  []string{"text/x-twig"},
		Extensions: []string{},
		Aliases:    []string{},
	},
	{
		Name:       "Web IDL",
		Mode:       "webidl",
		MimeTypes:  []string{"text/x-webidl"},
		Extensions: []string{"webidl"},
		Aliases:    []string{},
	},
	{
		Name:       "VB.NET",
		Mode:       "vb",
		MimeTypes:  []string{"text/x-vb"},
		Extensions: []string{"vb"},
		Aliases:    []string{},
	},
	{
		Name:       "VBScript",
		Mode:       "vbscript",
		MimeTypes:  []string{"text/vbscript"},
		Extensions: []string{"vbs"},
		Aliases:    []string{},
	},
	{
		Name:       "Velocity",
		Mode:       "velocity",
		MimeTypes:  []string{"text/velocity"},
		Extensions: []string{"vtl"},
		Aliases:    []string{},
	},
	{
		Name:       "Verilog",
		Mode:       "verilog",
		MimeTypes:  []string{"text/x-verilog"},
		Extensions: []string{"v"},
		Aliases:    []string{},
	},
	{
		Name:       "VHDL",
		Mode:       "vhdl",
		MimeTypes:  []string{"text/x-vhdl"},
		Extensions: []string{"vhd", "vhdl"},
		Aliases:    []string{},
	},
	{
		Name:       "Vue.js Component",
		Mode:       "vue",
		MimeTypes:  []string{"script/x-vue", "text/x-vue"},
		Extensions: []string{"vue"},
		Aliases:    []string{},
	},
	{
		Name:       "XML",
		Mode:       "xml",
		MimeTypes:  []string{"application/xml", "text/xml"},
		Extensions: []string{"xml", "xsl", "xsd", "svg"},
		Aliases:    []string{"rss", "wsdl", "xsd"},
	},
	{
		Name:       "XQuery",
		Mode:       "xquery",
		MimeTypes:  []string{"application/xquery"},
		Extensions: []string{"xy", "xquery"},
		Aliases:    []string{},
	},
	{
		Name:       "Yacas",
		Mode:       "yacas",
		MimeTypes:  []string{"text/x-yacas"},
		Extensions: []string{"ys"},
		Aliases:    []string{},
	},
	{
		Name:       "YAML",
		Mode:       "yaml",
		MimeTypes:  []string{"text/x-yaml", "text/yaml"},
		Extensions: []string{"yaml", "yml"},
		Aliases:    []string{"yml"},
	},
	{
		Name:       "Z80",
		Mode:       "z80",
		MimeTypes:  []string{"text/x-z80"},
		Extensions: []string{"z80"},
		Aliases:    []string{},
	},
	{
		Name:       "mscgen",
		Mode:       "mscgen",
		MimeTypes:  []string{"text/x-mscgen"},
		Extensions: []string{"mscgen", "mscin", "msc"},
		Aliases:    []string{},
	},
	{
		Name:       "xu",
		Mode:       "mscgen",
		MimeTypes:  []string{"text/x-xu"},
		Extensions: []string{"xu"},
		Aliases:    []string{},
	},
	{
		Name:       "msgenny",
		Mode:       "mscgen",
		MimeTypes:  []string{"text/x-msgenny"},
		Extensions: []string{"msgenny"},
		Aliases:    []string{},
	},
	{
		Name:       "WebAssembly",
		Mode:       "wast",
		MimeTypes:  []string{"text/webassembly"},
		Extensions: []string{"wat", "wast"},
		Aliases:    []string{},
	},
}
