package monaco

// revive:disable:line-length-limit

// Languages ...
var Languages = []Language{
	{
		ID:         "plain",
		Name:       "Plain text",
		Aliases:    []string{},
		Extensions: []string{".txt"},
		Filenames:  []string{},
	},
	{
		ID:         "abap",
		Name:       "ABAP",
		Aliases:    []string{"ABAP"},
		Extensions: []string{".abap"},
		Filenames:  []string{},
	},
	{
		ID:         "apex",
		Name:       "Apex",
		Aliases:    []string{"apex"},
		Extensions: []string{".cls"},
		Filenames:  []string{},
	},
	{
		ID:         "azcli",
		Name:       "Azure CLI",
		Aliases:    []string{"azcli"},
		Extensions: []string{".azcli"},
		Filenames:  []string{},
	},
	{
		ID:         "bat",
		Name:       "Batch",
		Aliases:    []string{"bat"},
		Extensions: []string{".bat", ".cmd"},
		Filenames:  []string{},
	},
	{
		ID:         "bicep",
		Name:       "Bicep",
		Aliases:    []string{},
		Extensions: []string{".bicep"},
		Filenames:  []string{},
	},
	{
		ID:         "cameligo",
		Name:       "Cameligo",
		Aliases:    []string{},
		Extensions: []string{".mligo"},
		Filenames:  []string{},
	},
	{
		ID:         "clojure",
		Name:       "Clojure",
		Aliases:    []string{"Clojure"},
		Extensions: []string{".clj", ".cljs", ".cljc", ".edn"},
		Filenames:  []string{},
	},
	{
		ID:         "coffeescript",
		Name:       "CoffeeScript",
		Aliases:    []string{"coffeescript", "coffee"},
		Extensions: []string{".coffee"},
		Filenames:  []string{},
	},
	{
		ID:         "c",
		Name:       "C",
		Aliases:    []string{"c"},
		Extensions: []string{".c", ".h"},
		Filenames:  []string{},
	},
	{
		ID:         "cpp",
		Name:       "C++",
		Aliases:    []string{"Cpp", "cpp"},
		Extensions: []string{".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx"},
		Filenames:  []string{},
	},
	{
		ID:         "csharp",
		Name:       "C#",
		Aliases:    []string{"csharp"},
		Extensions: []string{".cs", ".csx", ".cake"},
		Filenames:  []string{},
	},
	{
		ID:         "csp",
		Name:       "CSP",
		Aliases:    []string{"csp"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "css",
		Name:       "CSS",
		Aliases:    []string{"css"},
		Extensions: []string{".css"},
		Filenames:  []string{},
	},
	{
		ID:         "cypher",
		Name:       "Cypher",
		Aliases:    []string{"OpenCypher"},
		Extensions: []string{".cypher", ".cyp"},
		Filenames:  []string{},
	},
	{
		ID:         "dart",
		Name:       "Dart",
		Aliases:    []string{"dart"},
		Extensions: []string{".dart"},
		Filenames:  []string{},
	},
	{
		ID:         "dockerfile",
		Name:       "Dockerfile",
		Aliases:    []string{},
		Extensions: []string{".dockerfile"},
		Filenames:  []string{"Dockerfile"},
	},
	{
		ID:         "ecl",
		Name:       "ECL",
		Aliases:    []string{"Ecl", "ecl"},
		Extensions: []string{".ecl"},
		Filenames:  []string{},
	},
	{
		ID:         "elixir",
		Name:       "Elixir",
		Aliases:    []string{"elixir", "ex"},
		Extensions: []string{".ex", ".exs"},
		Filenames:  []string{},
	},
	{
		ID:         "flow9",
		Name:       "Flow9",
		Aliases:    []string{"Flow", "flow9", "flow"},
		Extensions: []string{".flow"},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2",
		Name:       "FreeMarker2",
		Aliases:    []string{"Apache FreeMarker2"},
		Extensions: []string{".ftl", ".ftlh", ".ftlx"},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2.tag-angle.interpolation-dollar",
		Name:       "FreeMarker2 (Angle/Dollar)",
		Aliases:    []string{"Apache FreeMarker2 (Angle/Dollar)"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2.tag-bracket.interpolation-dollar",
		Name:       "FreeMarker2 (Bracket/Dollar)",
		Aliases:    []string{"Apache FreeMarker2 (Bracket/Dollar)"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2.tag-angle.interpolation-bracket",
		Name:       "FreeMarker2 (Angle/Bracket)",
		Aliases:    []string{"Apache FreeMarker2 (Angle/Bracket)"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2.tag-bracket.interpolation-bracket",
		Name:       "FreeMarker2 (Bracket/Bracket)",
		Aliases:    []string{"Apache FreeMarker2 (Bracket/Bracket)"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2.tag-auto.interpolation-dollar",
		Name:       "FreeMarker2 (Auto/Dollar)",
		Aliases:    []string{"Apache FreeMarker2 (Auto/Dollar)"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "freemarker2.tag-auto.interpolation-bracket",
		Name:       "FreeMarker2 (Auto/Bracket)",
		Aliases:    []string{"Apache FreeMarker2 (Auto/Bracket)"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "fsharp",
		Name:       "F#",
		Aliases:    []string{"FSharp", "fsharp"},
		Extensions: []string{".fs", ".fsi", ".ml", ".mli", ".fsx", ".fsscript"},
		Filenames:  []string{},
	},
	{
		ID:         "go",
		Name:       "Go",
		Aliases:    []string{},
		Extensions: []string{".go"},
		Filenames:  []string{},
	},
	{
		ID:         "graphql",
		Name:       "GraphQL",
		Aliases:    []string{"graphql", "gql"},
		Extensions: []string{".graphql", ".gql"},
		Filenames:  []string{},
	},
	{
		ID:         "handlebars",
		Name:       "Handlebars",
		Aliases:    []string{"handlebars", "hbs"},
		Extensions: []string{".handlebars", ".hbs"},
		Filenames:  []string{},
	},
	{
		ID:         "hcl",
		Name:       "Terraform",
		Aliases:    []string{"tf", "HCL", "hcl"},
		Extensions: []string{".tf", ".tfvars", ".hcl"},
		Filenames:  []string{},
	},
	{
		ID:         "html",
		Name:       "HTML",
		Aliases:    []string{"htm", "html", "xhtml"},
		Extensions: []string{".html", ".htm", ".shtml", ".xhtml", ".mdoc", ".jsp", ".asp", ".aspx", ".jshtm"},
		Filenames:  []string{},
	},
	{
		ID:         "ini",
		Name:       "Ini",
		Aliases:    []string{"ini"},
		Extensions: []string{".ini", ".properties", ".gitconfig"},
		Filenames:  []string{"config", ".gitattributes", ".gitconfig", ".editorconfig"},
	},
	{
		ID:         "java",
		Name:       "Java",
		Aliases:    []string{"java"},
		Extensions: []string{".java", ".jav"},
		Filenames:  []string{},
	},
	{
		ID:         "javascript",
		Name:       "JavaScript",
		Aliases:    []string{"javascript", "js"},
		Extensions: []string{".js", ".es6", ".jsx", ".mjs", ".cjs"},
		Filenames:  []string{"jakefile"},
	},
	{
		ID:         "julia",
		Name:       "Julia",
		Aliases:    []string{"Julia"},
		Extensions: []string{".jl"},
		Filenames:  []string{},
	},
	{
		ID:         "kotlin",
		Name:       "Kotlin",
		Aliases:    []string{"kotlin"},
		Extensions: []string{".kt"},
		Filenames:  []string{},
	},
	{
		ID:         "less",
		Name:       "Less",
		Aliases:    []string{"less"},
		Extensions: []string{".less"},
		Filenames:  []string{},
	},
	{
		ID:         "lexon",
		Name:       "Lexon",
		Aliases:    []string{},
		Extensions: []string{".lex"},
		Filenames:  []string{},
	},
	{
		ID:         "liquid",
		Name:       "Liquid",
		Aliases:    []string{"liquid"},
		Extensions: []string{".liquid", ".html.liquid"},
		Filenames:  []string{},
	},
	{
		ID:         "lua",
		Name:       "Lua",
		Aliases:    []string{"lua"},
		Extensions: []string{".lua"},
		Filenames:  []string{},
	},
	{
		ID:         "m3",
		Name:       "Modula-3",
		Aliases:    []string{"Modula3", "modula3", "m3"},
		Extensions: []string{".m3", ".i3", ".mg", ".ig"},
		Filenames:  []string{},
	},
	{
		ID:         "markdown",
		Name:       "Markdown",
		Aliases:    []string{"markdown"},
		Extensions: []string{".md", ".markdown", ".mdown", ".mkdn", ".mkd", ".mdwn", ".mdtxt", ".mdtext"},
		Filenames:  []string{},
	},
	{
		ID:         "mips",
		Name:       "MIPS",
		Aliases:    []string{"MIPS-V"},
		Extensions: []string{".s"},
		Filenames:  []string{},
	},
	{
		ID:         "msdax",
		Name:       "DAX",
		Aliases:    []string{"MSDAX"},
		Extensions: []string{".dax", ".msdax"},
		Filenames:  []string{},
	},
	{
		ID:         "mysql",
		Name:       "MySQL",
		Aliases:    []string{"mysql"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "objective-c",
		Name:       "Objective-C",
		Aliases:    []string{},
		Extensions: []string{".m"},
		Filenames:  []string{},
	},
	{
		ID:         "pascal",
		Name:       "Pascal",
		Aliases:    []string{"pas"},
		Extensions: []string{".pas", ".p", ".pp"},
		Filenames:  []string{},
	},
	{
		ID:         "pascaligo",
		Name:       "Pascaligo",
		Aliases:    []string{"ligo"},
		Extensions: []string{".ligo"},
		Filenames:  []string{},
	},
	{
		ID:         "perl",
		Name:       "Perl",
		Aliases:    []string{"pl"},
		Extensions: []string{".pl"},
		Filenames:  []string{},
	},
	{
		ID:         "pgsql",
		Name:       "PostgreSQL",
		Aliases:    []string{"postgres", "pg", "postgre"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "php",
		Name:       "PHP",
		Aliases:    []string{"php"},
		Extensions: []string{".php", ".php4", ".php5", ".phtml", ".ctp"},
		Filenames:  []string{},
	},
	{
		ID:         "postiats",
		Name:       "ATS",
		Aliases:    []string{"ATS/Postiats"},
		Extensions: []string{".dats", ".sats", ".hats"},
		Filenames:  []string{},
	},
	{
		ID:         "powerquery",
		Name:       "PQ",
		Aliases:    []string{"M", "Power Query", "Power Query M"},
		Extensions: []string{".pq", ".pqm"},
		Filenames:  []string{},
	},
	{
		ID:         "powershell",
		Name:       "PowerShell",
		Aliases:    []string{"powershell", "ps", "ps1"},
		Extensions: []string{".ps1", ".psm1", ".psd1"},
		Filenames:  []string{},
	},
	{
		ID:         "proto",
		Name:       "Protobuf",
		Aliases:    []string{"Protocol Buffers"},
		Extensions: []string{".proto"},
		Filenames:  []string{},
	},
	{
		ID:         "pug",
		Name:       "Pug",
		Aliases:    []string{"Jade", "jade"},
		Extensions: []string{".jade", ".pug"},
		Filenames:  []string{},
	},
	{
		ID:         "python",
		Name:       "Python",
		Aliases:    []string{"py"},
		Extensions: []string{".py", ".rpy", ".pyw", ".cpy", ".gyp", ".gypi"},
		Filenames:  []string{},
	},
	{
		ID:         "qsharp",
		Name:       "Q#",
		Aliases:    []string{"qsharp"},
		Extensions: []string{".qs"},
		Filenames:  []string{},
	},
	{
		ID:         "r",
		Name:       "R",
		Aliases:    []string{"r"},
		Extensions: []string{".r", ".rhistory", ".rmd", ".rprofile", ".rt"},
		Filenames:  []string{},
	},
	{
		ID:         "razor",
		Name:       "Razor",
		Aliases:    []string{"razor"},
		Extensions: []string{".cshtml"},
		Filenames:  []string{},
	},
	{
		ID:         "redis",
		Name:       "Redis",
		Aliases:    []string{},
		Extensions: []string{".redis"},
		Filenames:  []string{},
	},
	{
		ID:         "redshift",
		Name:       "Redshift",
		Aliases:    []string{"redshift"},
		Extensions: []string{},
		Filenames:  []string{},
	},
	{
		ID:         "restructuredtext",
		Name:       "ReStructuredText",
		Aliases:    []string{"restructuredtext"},
		Extensions: []string{".rst"},
		Filenames:  []string{},
	},
	{
		ID:         "ruby",
		Name:       "Ruby",
		Aliases:    []string{"rb"},
		Extensions: []string{".rb", ".rbx", ".rjs", ".gemspec", ".pp"},
		Filenames:  []string{"rakefile", "Gemfile"},
	},
	{
		ID:         "rust",
		Name:       "Rust",
		Aliases:    []string{"rust"},
		Extensions: []string{".rs", ".rlib"},
		Filenames:  []string{},
	},
	{
		ID:         "sb",
		Name:       "Small Basic",
		Aliases:    []string{"sb"},
		Extensions: []string{".sb"},
		Filenames:  []string{},
	},
	{
		ID:         "scala",
		Name:       "Scala",
		Aliases:    []string{"scala", "SBT", "Sbt", "sbt", "Dotty", "dotty"},
		Extensions: []string{".scala", ".sc", ".sbt"},
		Filenames:  []string{},
	},
	{
		ID:         "scheme",
		Name:       "Scheme",
		Aliases:    []string{"Scheme"},
		Extensions: []string{".scm", ".ss", ".sch", ".rkt"},
		Filenames:  []string{},
	},
	{
		ID:         "scss",
		Name:       "Sass",
		Aliases:    []string{"sass", "scss"},
		Extensions: []string{".scss"},
		Filenames:  []string{},
	},
	{
		ID:         "shell",
		Name:       "Shell",
		Aliases:    []string{"sh"},
		Extensions: []string{".sh", ".bash"},
		Filenames:  []string{},
	},
	{
		ID:         "sol",
		Name:       "Solidity",
		Aliases:    []string{"solidity", "Solidity"},
		Extensions: []string{".sol"},
		Filenames:  []string{},
	},
	{
		ID:         "aes",
		Name:       "Sophia",
		Aliases:    []string{"sophia", "Sophia"},
		Extensions: []string{".aes"},
		Filenames:  []string{},
	},
	{
		ID:         "sparql",
		Name:       "SPARQL",
		Aliases:    []string{"SPARQL"},
		Extensions: []string{".rq"},
		Filenames:  []string{},
	},
	{
		ID:         "sql",
		Name:       "SQL",
		Aliases:    []string{},
		Extensions: []string{".sql"},
		Filenames:  []string{},
	},
	{
		ID:         "st",
		Name:       "StructuredText",
		Aliases:    []string{"scl", "stl"},
		Extensions: []string{".st", ".iecst", ".iecplc", ".lc3lib"},
		Filenames:  []string{},
	},
	{
		ID:         "swift",
		Name:       "Swift",
		Aliases:    []string{"swift"},
		Extensions: []string{".swift"},
		Filenames:  []string{},
	},
	{
		ID:         "systemverilog",
		Name:       "SV",
		Aliases:    []string{"sv", "SystemVerilog", "systemverilog"},
		Extensions: []string{".sv", ".svh"},
		Filenames:  []string{},
	},
	{
		ID:         "verilog",
		Name:       "V",
		Aliases:    []string{"v", "Verilog", "verilog"},
		Extensions: []string{".v", ".vh"},
		Filenames:  []string{},
	},
	{
		ID:         "tcl",
		Name:       "Tcl",
		Aliases:    []string{"Tcl", "tcltk", "TclTk", "tcl/tk", "Tcl/Tk"},
		Extensions: []string{".tcl"},
		Filenames:  []string{},
	},
	{
		ID:         "twig",
		Name:       "Twig",
		Aliases:    []string{"twig"},
		Extensions: []string{".twig"},
		Filenames:  []string{},
	},
	{
		ID:         "typescript",
		Name:       "TypeScript",
		Aliases:    []string{"ts", "typescript"},
		Extensions: []string{".ts", ".tsx"},
		Filenames:  []string{},
	},
	{
		ID:         "vb",
		Name:       "Visual Basic",
		Aliases:    []string{"vb"},
		Extensions: []string{".vb"},
		Filenames:  []string{},
	},
	{
		ID:         "xml",
		Name:       "XML",
		Aliases:    []string{"xml"},
		Extensions: []string{".xml", ".dtd", ".ascx", ".csproj", ".config", ".wxi", ".wxl", ".wxs", ".xaml", ".svg", ".svgz", ".opf", ".xsl"},
		Filenames:  []string{},
	},
	{
		ID:         "yaml",
		Name:       "YAML",
		Aliases:    []string{"yaml", "YML", "yml"},
		Extensions: []string{".yaml", ".yml"},
		Filenames:  []string{},
	},
}
